### ISSUE TITLE
Not all config variables configurable

### ISSUE THREAD

**Issue by exptom** [Conzar/ckan-puppet#5]
I'm trying to install this module but having a few problems.
Not all the variables in config.pp are configurable. $backup = '/backup' is causing me issues as I already have a /backup directory on my servers that is created by puppet so this module causes puppet to complain about a duplicate declaration. I would like to be able to configure it to backup to /backup/ckan.

Also only the postgres admin password is configurable. It would be useful to be able to set the password for the ckan user rather than just being set to "pass".

**Comment by Conzar** [comment]
I will fix these issues soon.

**Comment by Conzar** [comment]
I have updated the puppet module to add support for both the backup dir and the ckan database user password.  See [commit 781799ff3dc3896218ed50acc45d321510fe66c1](https://github.com/Conzar/ckan-puppet/commit/781799ff3dc3896218ed50acc45d321510fe66c1)

**Comment by exptom** [comment]
Many thanks for this! Could you do a 1.0.10 tag so that I can get this via the forge.

**Comment by Conzar** [comment]
So do you want me to add a git tag for github?  Or to release a new version on puppet forge? 

I have released 1.0.10 on [puppet forge](https://forge.puppetlabs.com/conzar/ckan/readme).

**Comment by Conzar** [comment]
Please use build 1.0.11 as 1.0.10 has a problem with the connection string in the ckan.ini.  Build 1.0.11 is available on puppet forge too.
