### ISSUE TITLE
Ubuntu 14.04

### ISSUE THREAD

**Issue by Vanuan** [Conzar/ckan-puppet#6]
> Note, Ubuntu 14.04 has been tested and currently doesn't install properly.

What are problems with that?

**Comment by Vanuan** [comment]
This command helps:
```
cp `which python2.7` /usr/lib/ckan/default/bin/python
```

**Comment by Conzar** [comment]
Currently, package installation of ckan does not work with Ubuntu 14.04.  See: https://github.com/ckan/ckan/issues/1651

The only way at this point to get ckan working on ubuntu 14.04 is to use the src install.  That will require some reworking of the ckan puppet module. I currently have other tasks to improve the ckan module and so this will have to wait.  It could be that later version of ckan (2.3 or 2.4) will support ubuntu 14.04 and so, that would mean I don't have to use the source install method too.

**Comment by Vanuan** [comment]
np. I've got some better experience with Chef: https://github.com/okfn/ckan-chef

**Comment by Conzar** [comment]
That only works with Ubuntu 12.04 as well.  So it won't solve your problem.  The problem is the deb file doesn't work with Ubuntu 14.04 (ie because of the compiler they use).  If you want to use Ubuntu 14.04, you will have to re-implement the chef module.

**Comment by Vanuan** [comment]
Nope, it uses source install. I've got it working: https://github.com/datagovua/ckan-vagrant-chef

**Comment by Conzar** [comment]
Congrats!
